name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: stable

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ Decode keystore from secret
      - name: Setup Release Keystore
      #need to add this in the secrets in github
        run: |
          mkdir -p android/key
          echo "${{ secrets.RELEASE_KEY }}" | base64 --decode > android/key/my-release-key.jks

      # 5️⃣ Skip widget tests in CI
      - name: Skip widget tests in CI
        run: echo "Skipping widget tests because Firebase is not initialized in CI"

      # 6️⃣ Build APK
      - name: Build APK
        run: flutter build apk --release

      # 7️⃣ Build AAB
      - name: Build AAB
        run: flutter build appbundle --release

      # 8️⃣ Verify AAB exists
      - name: Verify AAB exists
        run: ls -lh build/app/outputs/bundle/release/

      # 9️⃣ Upload artifacts (optional)
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab-${{ github.run_number }}
          path: build/app/outputs/bundle/release/app-release.aab

      # 🔟 Deploy to Google Play
      - name: Deploy to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }} #need to add this in the secrets in github
          packageName: com.diaaldin.bastahaap
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal #change to production when ready to release
          status: draft #change to complete when ready to release
          inAppUpdatePriority: 0
