name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build APK & AAB
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Skip widget tests in CI
      run: echo "Skipping widget tests because Firebase is not initialized in CI"

    - name: Build APK
      run: flutter build apk --release

    - name: Build AAB
      run: flutter build appbundle --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk-${{ github.run_number }}
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Upload AAB artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-aab-${{ github.run_number }}
        path: build/app/outputs/bundle/release/app-release.aab