name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: stable

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ Skip widget tests in CI
      - name: Skip widget tests in CI
        run: echo "Skipping widget tests because Firebase is not initialized in CI"

      # 5️⃣ Build APK (optional)
      - name: Build APK
        run: flutter build apk --release

      # 6️⃣ Build AAB
      - name: Build AAB
        run: flutter build appbundle --release

      # 7️⃣ Verify AAB exists
      - name: Verify AAB exists
        run: ls -lh build/app/outputs/bundle/release/

      # 8️⃣ Upload artifacts (optional)
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab-${{ github.run_number }}
          path: build/app/outputs/bundle/release/app-release.aab

      # 9️⃣ Deploy to Google Play
      - name: Deploy to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.diaaldin.basta
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
          inAppUpdatePriority: 0
